# License system
verify:

  # Your api key here
  api: "4994153f292d7804c4173ab06515bca924659c4c"

  # Your license key here
  license: ""

# Violation logging
logging:

  # Should Intect send you ingame a message if a new update is available?
  alert-updates: true