name: Intect
version: ${project.version}
main: net.square.intect.Intect
authors: [ SquareCode ]
description: Intect is an event- & packetbased cheat detection software, providing fair play
website: https://squarecode.de

commands:
  intect:
    aliases:
      - iac
  logs:
